### ISSUE TITLE
Create drop: always "failed" when creating via api (both prod and dev)

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-nfts#121]
E.g. drop id `3beed31f-3d74-40c3-8d67-9d273e9805dc`

**Comment by mpwsh** [comment]
Was able to replicate if you set a wallet that's not your treasury wallet as `creators.address` and set verified to `true`.

If instead i set it to `false` createDrop works. Wallet below is my phantom address.

```json
"creators": [{
  "address": "EddYHALSPtgyPjjUmUrsBbgrfqUz6r8p61NKRhj3QPn3",
  "share": 100,
  "verified": true
}],
```

API Responds with `Creating` but after a few seconds it fails to create the drop, also the 'failed'  message is not showing.



![Image](https://github.com/holaplex/hub-nfts/assets/13471075/5371fc0d-2e4b-485f-b657-bd05fb8d6ed8)



API is also allowing you to set `share` to values above 100, or combining not summing 100.
createDrop fails in this case too, but API responds with `Creating` and fails silently


Response from API after setting share to 150
```json
{
	"data": {
		"createDrop": {
			"drop": {
				"id": "8ff0cb3b-092e-4978-8b1f-76d2d9de085c",
				"price": 0,
				"status": "CREATING",
				"createdAt": "2023-06-23T16:42:30.048130+00:00",
				"startTime": null,
				"endTime": null,
				"collection": {
					"id": "d4fbd111-965c-44ce-865c-2e27eca8773c",
					"supply": 1,
					"totalMints": 0,
					"creators": [
						{
							"share": 150,
							"verified": false,
							"address": "EddYHALSPtgyPjjUmUrsBbgrfqUz6r8p61NKRhj3QPn3"
						}
					],
					"metadataJson": {
						"id": "d4fbd111-965c-44ce-865c-2e27eca8773c",
						"name": "CatJuiceNotVerified",
						"image": "https://assets.holaplex.tools/ipfs/bafkreicwjye6zu5x52564w6a5h5fqqchh2qjxmhyfqbmt63wrmbiobvppa?width=0",
						"description": "happycat",
						"symbol": "CATJ",
						"__typename": "MetadataJson"
					},
					"__typename": "Collection"
				},
				"__typename": "Drop"
			},
			"__typename": "CreateDropPayload"
		}
	}
}
```

**Comment by mpwsh** [comment]
More notes about this.
Fireblocks signs the transaction as completed, but its the RPC That's failing with:

For verified true on external wallets.
```
Program log: You cannot unilaterally verify another creator, they must sign"
```

For shares above 100:
```
"Program log: Share total must equal 100 for creator array",
```

**Comment by kespinola** [comment]
https://github.com/holaplex/hub-nfts/issues/123

Added validations for verification
