### ISSUE TITLE
Lowecase Polygon Addresses Before Saving to DB

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-nfts#138]
## Issue
Polygon addresses are case insensitive. Fireblocks and alchemy return different casing for the same address which is being interpreted by our system as 2 different wallets.

## Fix
Sanitize address by downcasing them before saving. Only for EVM chains. Solana address are case sensitive and should not be sanitized.

**Comment by imabdulbasit** [comment]
Already changed the columns to citext in hub-nfts-polygon 

Thinking to add a trigger  that saves addresses in lowercase for polygon in hub-nfts & hub-treasuries and we convert input address to lowercase when querying for polygon.
