### ISSUE TITLE
Collections Webhooks

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-nfts#147]
# Goal
Users can subscribe to webhooks when a collection is created or NFT minted to the collection.

**Comment by kespinola** [comment]
Events for publishing wehbooks.

https://github.com/holaplex/hub-schema-registry/pull/71/files

**Comment by kespinola** [comment]
Events being emitted from hub-nfts

https://github.com/holaplex/hub-nfts/pull/149

**Comment by imabdulbasit** [comment]
done
https://github.com/holaplex/hub-webhooks/pull/28
