### ISSUE TITLE
Hub - error in creating a drop

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-nfts#70]
On dev, got infinite spinner on "Start mint" button

![Image](https://user-images.githubusercontent.com/24394839/235254228-f783aea4-3dae-4c91-bec9-90281fd768da.png)

![Image](https://user-images.githubusercontent.com/24394839/235254289-9350237f-4977-42af-ae4e-7d4fe422f000.png)

project_id `833465c4-e95d-4868-9c52-923bd12a4032`

**Comment by kespinola** [comment]
@mackenziewildman I just created this with all the default but 5% royalties quick select. We'll lookup the what we can in the logs but do you recall what combination of inputs you used?

https://hub.holaplex.dev/projects/4263259b-5180-4f4f-98ae-a5012b258ef6/drops/40072a64-e7bf-4ecd-a410-e1eb93e8a0ac/holders

**Comment by mackenziewildman** [comment]
See screencast attached!

https://user-images.githubusercontent.com/24394839/235476749-84173876-8075-49f8-aecc-ff5cca4083d3.mov

**Comment by mackenziewildman** [comment]
I'm still getting an error here - see new screencast

https://user-images.githubusercontent.com/24394839/235788562-1be67e50-cf19-4e9a-8a15-84f49ac175b4.mov

**Comment by mackenziewildman** [comment]
I can get around this error by running
```
npm run reset
npm run generate
```

(it's coming up because I'm making a demo video to spin up locally)

**Comment by kespinola** [comment]
@mackenziewildman this ticket was for issues with creating drops after the new UI update. I'm closing it but please re-open if you encounter any issues creating or editing a drop.
