### ISSUE TITLE
Prevent Setting End Dates in the Past

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-nfts#99]
## Issue
Users can set the end date of their drop in the past.

## Desire
- [x] The API validates that end dates are in the future when present https://github.com/holaplex/hub-nfts/pull/96/files
- [x] The UI prevents user from setting a date in the past

## Screencast

https://user-images.githubusercontent.com/24394839/240422704-60a55f38-7e50-4ee3-b3fe-92f337bff959.mov

**Comment by alchemistgo87** [comment]
https://github.com/holaplex/hub/pull/202
